#############################################################################
# Makefile for building: RPi_Console
# Generated by qmake (3.0) (Qt 5.6.4)
# Project:  RPi_Console.pro
# Template: app
# Command: /Users/Roy/raspi/qtbase/bin/qmake -o Makefile RPi_Console.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /usr/local/linaro/arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc
CXX           = /usr/local/linaro/arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -march=armv7-a -marm -mthumb-interwork -mfpu=neon-vfpv4 -mtune=cortex-a7 -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/Users/Roy/raspi/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -march=armv7-a -marm -mthumb-interwork -mfpu=neon-vfpv4 -mtune=cortex-a7 -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/Users/Roy/raspi/sysroot -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/linux -I../../qtbase/include -I../../qtbase/include/QtCore -I. -I../../qtbase/mkspecs/devices/linux-rasp-pi2-g++
QMAKE         = /Users/Roy/raspi/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RPi_Console1.0.0
DISTDIR = /Users/Roy/raspi/projects/RPi_Console/.tmp/RPi_Console1.0.0
LINK          = /usr/local/linaro/arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath-link,/Users/Roy/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/Users/Roy/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/Users/Roy/raspi/sysroot/lib/arm-linux-gnueabihf -mfloat-abi=hard --sysroot=/Users/Roy/raspi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib
LIBS          = $(SUBLIBS) -L/Users/Roy/raspi/qtbase/lib -lQt5Core -lpthread 
AR            = /usr/local/linaro/arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /usr/local/linaro/arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Consolereader.cpp \
		../PCA9685/PCA9685.cpp moc_Consolereader.cpp
OBJECTS       = main.o \
		Consolereader.o \
		PCA9685.o \
		moc_Consolereader.o
DIST          = ../../qtbase/mkspecs/features/spec_pre.prf \
		../../qtbase/mkspecs/common/unix.conf \
		../../qtbase/mkspecs/common/linux.conf \
		../../qtbase/mkspecs/common/sanitize.conf \
		../../qtbase/mkspecs/common/gcc-base.conf \
		../../qtbase/mkspecs/common/gcc-base-unix.conf \
		../../qtbase/mkspecs/common/g++-base.conf \
		../../qtbase/mkspecs/common/g++-unix.conf \
		../../qtbase/mkspecs/qdevice.pri \
		../../qtbase/mkspecs/features/device_config.prf \
		../../qtbase/mkspecs/devices/common/linux_device_pre.conf \
		../../qtbase/mkspecs/devices/common/linux_device_post.conf \
		../../qtbase/mkspecs/devices/common/linux_arm_device_post.conf \
		../../qtbase/mkspecs/qconfig.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_bootstrap_dbus_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_concurrent_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_core_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_core.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_dbus.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_dbus_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_eglfs_device_lib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_network_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_network.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_opengl.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_platformsupport_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_sql.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_sql_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_xcb_qpa_lib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_zlib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_zlib_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_composeplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_cupsprintersupport.pri \
		../../qtbase/mkspecs/modules/qt_plugin_cupsprintersupport.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qconnmanbearer.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs-brcm-integration.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qeglfs-brcm-integration.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs-kms-integration.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qeglfs-kms-integration.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qeglfs.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevkeyboardplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevmouseplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevtabletplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevtouchplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qico.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qlibinputplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qlibinputplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qlinuxfb.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qminimalegl.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qminimalegl.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qnmbearer.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qsqlodbc.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qsqltds.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qsqltds.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qxcb.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qxcb.pri \
		../../qtbase/mkspecs/modules/qt_tool_moc.pri \
		../../qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../qtbase/mkspecs/modules/qt_tool_rcc.pri \
		../../qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../qtbase/mkspecs/features/qt_functions.prf \
		../../qtbase/mkspecs/features/qt_config.prf \
		../../qtbase/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf \
		../../qtbase/mkspecs/features/spec_post.prf \
		../../qtbase/mkspecs/features/exclusive_builds.prf \
		../../qtbase/mkspecs/features/default_pre.prf \
		../../qtbase/mkspecs/features/resolve_config.prf \
		../../qtbase/mkspecs/features/default_post.prf \
		../../qtbase/mkspecs/features/warn_on.prf \
		../../qtbase/mkspecs/features/qt.prf \
		../../qtbase/mkspecs/features/resources.prf \
		../../qtbase/mkspecs/features/moc.prf \
		../../qtbase/mkspecs/features/unix/thread.prf \
		../../qtbase/mkspecs/features/file_copies.prf \
		../../qtbase/mkspecs/features/testcase_targets.prf \
		../../qtbase/mkspecs/features/exceptions.prf \
		../../qtbase/mkspecs/features/yacc.prf \
		../../qtbase/mkspecs/features/lex.prf \
		RPi_Console.pro Consolereader.h \
		../PCA9685/PCA9685.h main.cpp \
		Consolereader.cpp \
		../PCA9685/PCA9685.cpp
QMAKE_TARGET  = RPi_Console
DESTDIR       = 
TARGET        = RPi_Console


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RPi_Console.pro ../../qtbase/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf ../../qtbase/mkspecs/features/spec_pre.prf \
		../../qtbase/mkspecs/common/unix.conf \
		../../qtbase/mkspecs/common/linux.conf \
		../../qtbase/mkspecs/common/sanitize.conf \
		../../qtbase/mkspecs/common/gcc-base.conf \
		../../qtbase/mkspecs/common/gcc-base-unix.conf \
		../../qtbase/mkspecs/common/g++-base.conf \
		../../qtbase/mkspecs/common/g++-unix.conf \
		../../qtbase/mkspecs/qdevice.pri \
		../../qtbase/mkspecs/features/device_config.prf \
		../../qtbase/mkspecs/devices/common/linux_device_pre.conf \
		../../qtbase/mkspecs/devices/common/linux_device_post.conf \
		../../qtbase/mkspecs/devices/common/linux_arm_device_post.conf \
		../../qtbase/mkspecs/qconfig.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_bootstrap_dbus_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_concurrent_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_core_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_core.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_dbus.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_dbus_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_eglfs_device_lib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_network_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_network.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_opengl.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_platformsupport_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_sql.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_sql_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_xcb_qpa_lib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../qtbase/mkspecs/modules-inst/qt_lib_zlib_private.pri \
		../../qtbase/mkspecs/modules/qt_lib_zlib_private.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_composeplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_cupsprintersupport.pri \
		../../qtbase/mkspecs/modules/qt_plugin_cupsprintersupport.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qconnmanbearer.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs-brcm-integration.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qeglfs-brcm-integration.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs-kms-integration.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qeglfs-kms-integration.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qeglfs.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevkeyboardplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevmouseplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevtabletplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevtouchplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qico.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qlibinputplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qlibinputplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qlinuxfb.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qminimalegl.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qminimalegl.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qnmbearer.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qsqlodbc.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qsqltds.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qsqltds.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../qtbase/mkspecs/modules-inst/qt_plugin_qxcb.pri \
		../../qtbase/mkspecs/modules/qt_plugin_qxcb.pri \
		../../qtbase/mkspecs/modules/qt_tool_moc.pri \
		../../qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../qtbase/mkspecs/modules/qt_tool_rcc.pri \
		../../qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../qtbase/mkspecs/features/qt_functions.prf \
		../../qtbase/mkspecs/features/qt_config.prf \
		../../qtbase/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf \
		../../qtbase/mkspecs/features/spec_post.prf \
		../../qtbase/mkspecs/features/exclusive_builds.prf \
		../../qtbase/mkspecs/features/default_pre.prf \
		../../qtbase/mkspecs/features/resolve_config.prf \
		../../qtbase/mkspecs/features/default_post.prf \
		../../qtbase/mkspecs/features/warn_on.prf \
		../../qtbase/mkspecs/features/qt.prf \
		../../qtbase/mkspecs/features/resources.prf \
		../../qtbase/mkspecs/features/moc.prf \
		../../qtbase/mkspecs/features/unix/thread.prf \
		../../qtbase/mkspecs/features/file_copies.prf \
		../../qtbase/mkspecs/features/testcase_targets.prf \
		../../qtbase/mkspecs/features/exceptions.prf \
		../../qtbase/mkspecs/features/yacc.prf \
		../../qtbase/mkspecs/features/lex.prf \
		RPi_Console.pro \
		../../qtbase/lib/libQt5Core.prl
	$(QMAKE) -o Makefile RPi_Console.pro
../../qtbase/mkspecs/features/spec_pre.prf:
../../qtbase/mkspecs/common/unix.conf:
../../qtbase/mkspecs/common/linux.conf:
../../qtbase/mkspecs/common/sanitize.conf:
../../qtbase/mkspecs/common/gcc-base.conf:
../../qtbase/mkspecs/common/gcc-base-unix.conf:
../../qtbase/mkspecs/common/g++-base.conf:
../../qtbase/mkspecs/common/g++-unix.conf:
../../qtbase/mkspecs/qdevice.pri:
../../qtbase/mkspecs/features/device_config.prf:
../../qtbase/mkspecs/devices/common/linux_device_pre.conf:
../../qtbase/mkspecs/devices/common/linux_device_post.conf:
../../qtbase/mkspecs/devices/common/linux_arm_device_post.conf:
../../qtbase/mkspecs/qconfig.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_bootstrap_dbus_private.pri:
../../qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri:
../../qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_concurrent_private.pri:
../../qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_core.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_core_private.pri:
../../qtbase/mkspecs/modules/qt_lib_core.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_dbus.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_dbus_private.pri:
../../qtbase/mkspecs/modules/qt_lib_dbus.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_eglfs_device_lib_private.pri:
../../qtbase/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_gui.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri:
../../qtbase/mkspecs/modules/qt_lib_gui.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_network.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_network_private.pri:
../../qtbase/mkspecs/modules/qt_lib_network.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_opengl.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri:
../../qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri:
../../qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_platformsupport_private.pri:
../../qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri:
../../qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_sql.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_sql_private.pri:
../../qtbase/mkspecs/modules/qt_lib_sql.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_testlib.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri:
../../qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_widgets.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri:
../../qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_xcb_qpa_lib_private.pri:
../../qtbase/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_xml.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri:
../../qtbase/mkspecs/modules/qt_lib_xml.pri:
../../qtbase/mkspecs/modules-inst/qt_lib_zlib_private.pri:
../../qtbase/mkspecs/modules/qt_lib_zlib_private.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_composeplatforminputcontextplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_cupsprintersupport.pri:
../../qtbase/mkspecs/modules/qt_plugin_cupsprintersupport.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_ibusplatforminputcontextplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qconnmanbearer.pri:
../../qtbase/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs-brcm-integration.pri:
../../qtbase/mkspecs/modules/qt_plugin_qeglfs-brcm-integration.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs-kms-integration.pri:
../../qtbase/mkspecs/modules/qt_plugin_qeglfs-kms-integration.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qeglfs.pri:
../../qtbase/mkspecs/modules/qt_plugin_qeglfs.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevkeyboardplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevmouseplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevtabletplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qevdevtouchplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri:
../../qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri:
../../qtbase/mkspecs/modules/qt_plugin_qgif.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qico.pri:
../../qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri:
../../qtbase/mkspecs/modules/qt_plugin_qjpeg.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qlibinputplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_qlibinputplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qlinuxfb.pri:
../../qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri:
../../qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qminimalegl.pri:
../../qtbase/mkspecs/modules/qt_plugin_qminimalegl.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qnmbearer.pri:
../../qtbase/mkspecs/modules/qt_plugin_qnmbearer.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri:
../../qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri:
../../qtbase/mkspecs/modules/qt_plugin_qsqlite.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qsqlodbc.pri:
../../qtbase/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qsqltds.pri:
../../qtbase/mkspecs/modules/qt_plugin_qsqltds.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri:
../../qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../qtbase/mkspecs/modules-inst/qt_plugin_qxcb.pri:
../../qtbase/mkspecs/modules/qt_plugin_qxcb.pri:
../../qtbase/mkspecs/modules/qt_tool_moc.pri:
../../qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri:
../../qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri:
../../qtbase/mkspecs/modules/qt_tool_qlalr.pri:
../../qtbase/mkspecs/modules/qt_tool_rcc.pri:
../../qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../qtbase/mkspecs/modules/qt_tool_uic.pri:
../../qtbase/mkspecs/features/qt_functions.prf:
../../qtbase/mkspecs/features/qt_config.prf:
../../qtbase/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf:
../../qtbase/mkspecs/features/spec_post.prf:
../../qtbase/mkspecs/features/exclusive_builds.prf:
../../qtbase/mkspecs/features/default_pre.prf:
../../qtbase/mkspecs/features/resolve_config.prf:
../../qtbase/mkspecs/features/default_post.prf:
../../qtbase/mkspecs/features/warn_on.prf:
../../qtbase/mkspecs/features/qt.prf:
../../qtbase/mkspecs/features/resources.prf:
../../qtbase/mkspecs/features/moc.prf:
../../qtbase/mkspecs/features/unix/thread.prf:
../../qtbase/mkspecs/features/file_copies.prf:
../../qtbase/mkspecs/features/testcase_targets.prf:
../../qtbase/mkspecs/features/exceptions.prf:
../../qtbase/mkspecs/features/yacc.prf:
../../qtbase/mkspecs/features/lex.prf:
RPi_Console.pro:
../../qtbase/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile RPi_Console.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Consolereader.h ../PCA9685/PCA9685.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Consolereader.cpp ../PCA9685/PCA9685.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Consolereader.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Consolereader.cpp
moc_Consolereader.cpp: ../../qtbase/include/QtCore/QThread \
		../../qtbase/include/QtCore/qthread.h \
		../../qtbase/src/corelib/thread/qthread.h \
		../../qtbase/include/QtCore/qobject.h \
		../../qtbase/src/corelib/kernel/qobject.h \
		../../qtbase/include/QtCore/qobjectdefs.h \
		../../qtbase/src/corelib/kernel/qobjectdefs.h \
		../../qtbase/include/QtCore/qnamespace.h \
		../../qtbase/src/corelib/global/qnamespace.h \
		../../qtbase/include/QtCore/qglobal.h \
		../../qtbase/src/corelib/global/qglobal.h \
		../../qtbase/include/QtCore/qconfig.h \
		../../qtbase/src/corelib/global/qconfig.h \
		../../qtbase/include/QtCore/qfeatures.h \
		../../qtbase/src/corelib/global/qfeatures.h \
		../../qtbase/include/QtCore/qsystemdetection.h \
		../../qtbase/src/corelib/global/qsystemdetection.h \
		../../qtbase/include/QtCore/qprocessordetection.h \
		../../qtbase/src/corelib/global/qprocessordetection.h \
		../../qtbase/include/QtCore/qcompilerdetection.h \
		../../qtbase/src/corelib/global/qcompilerdetection.h \
		../../qtbase/include/QtCore/qtypeinfo.h \
		../../qtbase/src/corelib/global/qtypeinfo.h \
		../../qtbase/include/QtCore/qtypetraits.h \
		../../qtbase/src/corelib/global/qtypetraits.h \
		../../qtbase/include/QtCore/qisenum.h \
		../../qtbase/src/corelib/global/qisenum.h \
		../../qtbase/include/QtCore/qsysinfo.h \
		../../qtbase/src/corelib/global/qsysinfo.h \
		../../qtbase/include/QtCore/qlogging.h \
		../../qtbase/src/corelib/global/qlogging.h \
		../../qtbase/include/QtCore/qflags.h \
		../../qtbase/src/corelib/global/qflags.h \
		../../qtbase/include/QtCore/qatomic.h \
		../../qtbase/src/corelib/thread/qatomic.h \
		../../qtbase/include/QtCore/qbasicatomic.h \
		../../qtbase/src/corelib/thread/qbasicatomic.h \
		../../qtbase/include/QtCore/qatomic_bootstrap.h \
		../../qtbase/src/corelib/arch/qatomic_bootstrap.h \
		../../qtbase/include/QtCore/qgenericatomic.h \
		../../qtbase/src/corelib/thread/qgenericatomic.h \
		../../qtbase/include/QtCore/qatomic_cxx11.h \
		../../qtbase/src/corelib/arch/qatomic_cxx11.h \
		../../qtbase/include/QtCore/qatomic_gcc.h \
		../../qtbase/src/corelib/arch/qatomic_gcc.h \
		../../qtbase/include/QtCore/qatomic_msvc.h \
		../../qtbase/src/corelib/arch/qatomic_msvc.h \
		../../qtbase/include/QtCore/qatomic_armv7.h \
		../../qtbase/src/corelib/arch/qatomic_armv7.h \
		../../qtbase/include/QtCore/qatomic_armv6.h \
		../../qtbase/src/corelib/arch/qatomic_armv6.h \
		../../qtbase/include/QtCore/qatomic_armv5.h \
		../../qtbase/src/corelib/arch/qatomic_armv5.h \
		../../qtbase/include/QtCore/qatomic_ia64.h \
		../../qtbase/src/corelib/arch/qatomic_ia64.h \
		../../qtbase/include/QtCore/qatomic_x86.h \
		../../qtbase/src/corelib/arch/qatomic_x86.h \
		../../qtbase/include/QtCore/qatomic_unix.h \
		../../qtbase/src/corelib/arch/qatomic_unix.h \
		../../qtbase/include/QtCore/qglobalstatic.h \
		../../qtbase/src/corelib/global/qglobalstatic.h \
		../../qtbase/include/QtCore/qmutex.h \
		../../qtbase/src/corelib/thread/qmutex.h \
		../../qtbase/include/QtCore/qnumeric.h \
		../../qtbase/src/corelib/global/qnumeric.h \
		../../qtbase/include/QtCore/qversiontagging.h \
		../../qtbase/src/corelib/global/qversiontagging.h \
		../../qtbase/include/QtCore/qobjectdefs_impl.h \
		../../qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../qtbase/include/QtCore/qstring.h \
		../../qtbase/src/corelib/tools/qstring.h \
		../../qtbase/include/QtCore/qchar.h \
		../../qtbase/src/corelib/tools/qchar.h \
		../../qtbase/include/QtCore/qbytearray.h \
		../../qtbase/src/corelib/tools/qbytearray.h \
		../../qtbase/include/QtCore/qrefcount.h \
		../../qtbase/src/corelib/tools/qrefcount.h \
		../../qtbase/include/QtCore/qarraydata.h \
		../../qtbase/src/corelib/tools/qarraydata.h \
		../../qtbase/include/QtCore/qstringbuilder.h \
		../../qtbase/src/corelib/tools/qstringbuilder.h \
		../../qtbase/include/QtCore/qlist.h \
		../../qtbase/src/corelib/tools/qlist.h \
		../../qtbase/include/QtCore/qalgorithms.h \
		../../qtbase/src/corelib/tools/qalgorithms.h \
		../../qtbase/include/QtCore/qiterator.h \
		../../qtbase/src/corelib/tools/qiterator.h \
		../../qtbase/include/QtCore/qhashfunctions.h \
		../../qtbase/src/corelib/tools/qhashfunctions.h \
		../../qtbase/include/QtCore/qpair.h \
		../../qtbase/src/corelib/tools/qpair.h \
		../../qtbase/include/QtCore/qbytearraylist.h \
		../../qtbase/src/corelib/tools/qbytearraylist.h \
		../../qtbase/include/QtCore/qstringlist.h \
		../../qtbase/src/corelib/tools/qstringlist.h \
		../../qtbase/include/QtCore/qregexp.h \
		../../qtbase/src/corelib/tools/qregexp.h \
		../../qtbase/include/QtCore/qstringmatcher.h \
		../../qtbase/src/corelib/tools/qstringmatcher.h \
		../../qtbase/include/QtCore/qcoreevent.h \
		../../qtbase/src/corelib/kernel/qcoreevent.h \
		../../qtbase/include/QtCore/qscopedpointer.h \
		../../qtbase/src/corelib/tools/qscopedpointer.h \
		../../qtbase/include/QtCore/qmetatype.h \
		../../qtbase/src/corelib/kernel/qmetatype.h \
		../../qtbase/include/QtCore/qvarlengtharray.h \
		../../qtbase/src/corelib/tools/qvarlengtharray.h \
		../../qtbase/include/QtCore/qcontainerfwd.h \
		../../qtbase/src/corelib/tools/qcontainerfwd.h \
		../../qtbase/include/QtCore/qobject_impl.h \
		../../qtbase/src/corelib/kernel/qobject_impl.h \
		Consolereader.h
	/Users/Roy/raspi/qtbase/bin/moc $(DEFINES) -I/Users/Roy/raspi/qtbase/mkspecs/devices/linux-rasp-pi2-g++ -I/Users/Roy/raspi/projects/RPi_Console -I/usr/include/linux -I/Users/Roy/raspi/qtbase/include -I/Users/Roy/raspi/qtbase/include/QtCore -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.9.1 -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.9.1/arm-linux-gnueabihf -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.9.1/backward -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.9.1/include -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.9.1/include-fixed -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include -I/Users/Roy/raspi/sysroot/usr/include/arm-linux-gnueabihf -I/Users/Roy/raspi/sysroot/usr/include Consolereader.h -o moc_Consolereader.cpp

compiler_moc_source_make_all: main.moc
compiler_moc_source_clean:
	-$(DEL_FILE) main.moc
main.moc: ../../qtbase/include/QtCore/QtCore \
		../../qtbase/include/QtCore/QtCoreDepends \
		../../qtbase/include/QtCore/qabstractanimation.h \
		../../qtbase/src/corelib/animation/qabstractanimation.h \
		../../qtbase/include/QtCore/qobject.h \
		../../qtbase/src/corelib/kernel/qobject.h \
		../../qtbase/include/QtCore/qobjectdefs.h \
		../../qtbase/src/corelib/kernel/qobjectdefs.h \
		../../qtbase/include/QtCore/qnamespace.h \
		../../qtbase/src/corelib/global/qnamespace.h \
		../../qtbase/include/QtCore/qglobal.h \
		../../qtbase/src/corelib/global/qglobal.h \
		../../qtbase/include/QtCore/qconfig.h \
		../../qtbase/src/corelib/global/qconfig.h \
		../../qtbase/include/QtCore/qfeatures.h \
		../../qtbase/src/corelib/global/qfeatures.h \
		../../qtbase/include/QtCore/qsystemdetection.h \
		../../qtbase/src/corelib/global/qsystemdetection.h \
		../../qtbase/include/QtCore/qprocessordetection.h \
		../../qtbase/src/corelib/global/qprocessordetection.h \
		../../qtbase/include/QtCore/qcompilerdetection.h \
		../../qtbase/src/corelib/global/qcompilerdetection.h \
		../../qtbase/include/QtCore/qtypeinfo.h \
		../../qtbase/src/corelib/global/qtypeinfo.h \
		../../qtbase/include/QtCore/qtypetraits.h \
		../../qtbase/src/corelib/global/qtypetraits.h \
		../../qtbase/include/QtCore/qisenum.h \
		../../qtbase/src/corelib/global/qisenum.h \
		../../qtbase/include/QtCore/qsysinfo.h \
		../../qtbase/src/corelib/global/qsysinfo.h \
		../../qtbase/include/QtCore/qlogging.h \
		../../qtbase/src/corelib/global/qlogging.h \
		../../qtbase/include/QtCore/qflags.h \
		../../qtbase/src/corelib/global/qflags.h \
		../../qtbase/include/QtCore/qatomic.h \
		../../qtbase/src/corelib/thread/qatomic.h \
		../../qtbase/include/QtCore/qbasicatomic.h \
		../../qtbase/src/corelib/thread/qbasicatomic.h \
		../../qtbase/include/QtCore/qatomic_bootstrap.h \
		../../qtbase/src/corelib/arch/qatomic_bootstrap.h \
		../../qtbase/include/QtCore/qgenericatomic.h \
		../../qtbase/src/corelib/thread/qgenericatomic.h \
		../../qtbase/include/QtCore/qatomic_cxx11.h \
		../../qtbase/src/corelib/arch/qatomic_cxx11.h \
		../../qtbase/include/QtCore/qatomic_gcc.h \
		../../qtbase/src/corelib/arch/qatomic_gcc.h \
		../../qtbase/include/QtCore/qatomic_msvc.h \
		../../qtbase/src/corelib/arch/qatomic_msvc.h \
		../../qtbase/include/QtCore/qatomic_armv7.h \
		../../qtbase/src/corelib/arch/qatomic_armv7.h \
		../../qtbase/include/QtCore/qatomic_armv6.h \
		../../qtbase/src/corelib/arch/qatomic_armv6.h \
		../../qtbase/include/QtCore/qatomic_armv5.h \
		../../qtbase/src/corelib/arch/qatomic_armv5.h \
		../../qtbase/include/QtCore/qatomic_ia64.h \
		../../qtbase/src/corelib/arch/qatomic_ia64.h \
		../../qtbase/include/QtCore/qatomic_x86.h \
		../../qtbase/src/corelib/arch/qatomic_x86.h \
		../../qtbase/include/QtCore/qatomic_unix.h \
		../../qtbase/src/corelib/arch/qatomic_unix.h \
		../../qtbase/include/QtCore/qglobalstatic.h \
		../../qtbase/src/corelib/global/qglobalstatic.h \
		../../qtbase/include/QtCore/qmutex.h \
		../../qtbase/src/corelib/thread/qmutex.h \
		../../qtbase/include/QtCore/qnumeric.h \
		../../qtbase/src/corelib/global/qnumeric.h \
		../../qtbase/include/QtCore/qversiontagging.h \
		../../qtbase/src/corelib/global/qversiontagging.h \
		../../qtbase/include/QtCore/qobjectdefs_impl.h \
		../../qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../qtbase/include/QtCore/qstring.h \
		../../qtbase/src/corelib/tools/qstring.h \
		../../qtbase/include/QtCore/qchar.h \
		../../qtbase/src/corelib/tools/qchar.h \
		../../qtbase/include/QtCore/qbytearray.h \
		../../qtbase/src/corelib/tools/qbytearray.h \
		../../qtbase/include/QtCore/qrefcount.h \
		../../qtbase/src/corelib/tools/qrefcount.h \
		../../qtbase/include/QtCore/qarraydata.h \
		../../qtbase/src/corelib/tools/qarraydata.h \
		../../qtbase/include/QtCore/qstringbuilder.h \
		../../qtbase/src/corelib/tools/qstringbuilder.h \
		../../qtbase/include/QtCore/qlist.h \
		../../qtbase/src/corelib/tools/qlist.h \
		../../qtbase/include/QtCore/qalgorithms.h \
		../../qtbase/src/corelib/tools/qalgorithms.h \
		../../qtbase/include/QtCore/qiterator.h \
		../../qtbase/src/corelib/tools/qiterator.h \
		../../qtbase/include/QtCore/qhashfunctions.h \
		../../qtbase/src/corelib/tools/qhashfunctions.h \
		../../qtbase/include/QtCore/qpair.h \
		../../qtbase/src/corelib/tools/qpair.h \
		../../qtbase/include/QtCore/qbytearraylist.h \
		../../qtbase/src/corelib/tools/qbytearraylist.h \
		../../qtbase/include/QtCore/qstringlist.h \
		../../qtbase/src/corelib/tools/qstringlist.h \
		../../qtbase/include/QtCore/qregexp.h \
		../../qtbase/src/corelib/tools/qregexp.h \
		../../qtbase/include/QtCore/qstringmatcher.h \
		../../qtbase/src/corelib/tools/qstringmatcher.h \
		../../qtbase/include/QtCore/qcoreevent.h \
		../../qtbase/src/corelib/kernel/qcoreevent.h \
		../../qtbase/include/QtCore/qscopedpointer.h \
		../../qtbase/src/corelib/tools/qscopedpointer.h \
		../../qtbase/include/QtCore/qmetatype.h \
		../../qtbase/src/corelib/kernel/qmetatype.h \
		../../qtbase/include/QtCore/qvarlengtharray.h \
		../../qtbase/src/corelib/tools/qvarlengtharray.h \
		../../qtbase/include/QtCore/qcontainerfwd.h \
		../../qtbase/src/corelib/tools/qcontainerfwd.h \
		../../qtbase/include/QtCore/qobject_impl.h \
		../../qtbase/src/corelib/kernel/qobject_impl.h \
		../../qtbase/include/QtCore/qanimationgroup.h \
		../../qtbase/src/corelib/animation/qanimationgroup.h \
		../../qtbase/include/QtCore/qparallelanimationgroup.h \
		../../qtbase/src/corelib/animation/qparallelanimationgroup.h \
		../../qtbase/include/QtCore/qpauseanimation.h \
		../../qtbase/src/corelib/animation/qpauseanimation.h \
		../../qtbase/include/QtCore/qpropertyanimation.h \
		../../qtbase/src/corelib/animation/qpropertyanimation.h \
		../../qtbase/include/QtCore/qvariantanimation.h \
		../../qtbase/src/corelib/animation/qvariantanimation.h \
		../../qtbase/include/QtCore/qeasingcurve.h \
		../../qtbase/src/corelib/tools/qeasingcurve.h \
		../../qtbase/include/QtCore/qvector.h \
		../../qtbase/src/corelib/tools/qvector.h \
		../../qtbase/include/QtCore/qpoint.h \
		../../qtbase/src/corelib/tools/qpoint.h \
		../../qtbase/include/QtCore/qvariant.h \
		../../qtbase/src/corelib/kernel/qvariant.h \
		../../qtbase/include/QtCore/qmap.h \
		../../qtbase/src/corelib/tools/qmap.h \
		../../qtbase/include/QtCore/qdebug.h \
		../../qtbase/src/corelib/io/qdebug.h \
		../../qtbase/include/QtCore/qhash.h \
		../../qtbase/src/corelib/tools/qhash.h \
		../../qtbase/include/QtCore/qtextstream.h \
		../../qtbase/src/corelib/io/qtextstream.h \
		../../qtbase/include/QtCore/qiodevice.h \
		../../qtbase/src/corelib/io/qiodevice.h \
		../../qtbase/include/QtCore/qlocale.h \
		../../qtbase/src/corelib/tools/qlocale.h \
		../../qtbase/include/QtCore/qshareddata.h \
		../../qtbase/src/corelib/tools/qshareddata.h \
		../../qtbase/include/QtCore/qset.h \
		../../qtbase/src/corelib/tools/qset.h \
		../../qtbase/include/QtCore/qcontiguouscache.h \
		../../qtbase/src/corelib/tools/qcontiguouscache.h \
		../../qtbase/include/QtCore/qsequentialanimationgroup.h \
		../../qtbase/src/corelib/animation/qsequentialanimationgroup.h \
		../../qtbase/include/QtCore/qtextcodec.h \
		../../qtbase/src/corelib/codecs/qtextcodec.h \
		../../qtbase/include/QtCore/qendian.h \
		../../qtbase/src/corelib/global/qendian.h \
		../../qtbase/include/QtCore/qlibraryinfo.h \
		../../qtbase/src/corelib/global/qlibraryinfo.h \
		../../qtbase/include/QtCore/qdatetime.h \
		../../qtbase/src/corelib/tools/qdatetime.h \
		../../qtbase/include/QtCore/qbuffer.h \
		../../qtbase/src/corelib/io/qbuffer.h \
		../../qtbase/include/QtCore/qdatastream.h \
		../../qtbase/src/corelib/io/qdatastream.h \
		../../qtbase/include/QtCore/qdir.h \
		../../qtbase/src/corelib/io/qdir.h \
		../../qtbase/include/QtCore/qfileinfo.h \
		../../qtbase/src/corelib/io/qfileinfo.h \
		../../qtbase/include/QtCore/qfile.h \
		../../qtbase/src/corelib/io/qfile.h \
		../../qtbase/include/QtCore/qfiledevice.h \
		../../qtbase/src/corelib/io/qfiledevice.h \
		../../qtbase/include/QtCore/qdiriterator.h \
		../../qtbase/src/corelib/io/qdiriterator.h \
		../../qtbase/include/QtCore/qfileselector.h \
		../../qtbase/src/corelib/io/qfileselector.h \
		../../qtbase/include/QtCore/QObject \
		../../qtbase/include/QtCore/QStringList \
		../../qtbase/include/QtCore/qfilesystemwatcher.h \
		../../qtbase/src/corelib/io/qfilesystemwatcher.h \
		../../qtbase/include/QtCore/qlockfile.h \
		../../qtbase/src/corelib/io/qlockfile.h \
		../../qtbase/include/QtCore/qloggingcategory.h \
		../../qtbase/src/corelib/io/qloggingcategory.h \
		../../qtbase/include/QtCore/qprocess.h \
		../../qtbase/src/corelib/io/qprocess.h \
		../../qtbase/include/QtCore/qresource.h \
		../../qtbase/src/corelib/io/qresource.h \
		../../qtbase/include/QtCore/qsavefile.h \
		../../qtbase/src/corelib/io/qsavefile.h \
		../../qtbase/include/QtCore/qsettings.h \
		../../qtbase/src/corelib/io/qsettings.h \
		../../qtbase/include/QtCore/qstandardpaths.h \
		../../qtbase/src/corelib/io/qstandardpaths.h \
		../../qtbase/include/QtCore/qstorageinfo.h \
		../../qtbase/src/corelib/io/qstorageinfo.h \
		../../qtbase/include/QtCore/qtemporarydir.h \
		../../qtbase/src/corelib/io/qtemporarydir.h \
		../../qtbase/include/QtCore/QScopedPointer \
		../../qtbase/include/QtCore/qtemporaryfile.h \
		../../qtbase/src/corelib/io/qtemporaryfile.h \
		../../qtbase/include/QtCore/qurl.h \
		../../qtbase/src/corelib/io/qurl.h \
		../../qtbase/include/QtCore/qurlquery.h \
		../../qtbase/src/corelib/io/qurlquery.h \
		../../qtbase/include/QtCore/qabstractitemmodel.h \
		../../qtbase/src/corelib/itemmodels/qabstractitemmodel.h \
		../../qtbase/include/QtCore/qabstractproxymodel.h \
		../../qtbase/src/corelib/itemmodels/qabstractproxymodel.h \
		../../qtbase/include/QtCore/qidentityproxymodel.h \
		../../qtbase/src/corelib/itemmodels/qidentityproxymodel.h \
		../../qtbase/include/QtCore/qitemselectionmodel.h \
		../../qtbase/src/corelib/itemmodels/qitemselectionmodel.h \
		../../qtbase/include/QtCore/qsortfilterproxymodel.h \
		../../qtbase/src/corelib/itemmodels/qsortfilterproxymodel.h \
		../../qtbase/include/QtCore/qstringlistmodel.h \
		../../qtbase/src/corelib/itemmodels/qstringlistmodel.h \
		../../qtbase/include/QtCore/qjsonarray.h \
		../../qtbase/src/corelib/json/qjsonarray.h \
		../../qtbase/include/QtCore/qjsonvalue.h \
		../../qtbase/src/corelib/json/qjsonvalue.h \
		../../qtbase/include/QtCore/qjsondocument.h \
		../../qtbase/src/corelib/json/qjsondocument.h \
		../../qtbase/include/QtCore/qjsonobject.h \
		../../qtbase/src/corelib/json/qjsonobject.h \
		../../qtbase/include/QtCore/qabstracteventdispatcher.h \
		../../qtbase/src/corelib/kernel/qabstracteventdispatcher.h \
		../../qtbase/include/QtCore/qeventloop.h \
		../../qtbase/src/corelib/kernel/qeventloop.h \
		../../qtbase/include/QtCore/qabstractnativeeventfilter.h \
		../../qtbase/src/corelib/kernel/qabstractnativeeventfilter.h \
		../../qtbase/include/QtCore/qbasictimer.h \
		../../qtbase/src/corelib/kernel/qbasictimer.h \
		../../qtbase/include/QtCore/qcoreapplication.h \
		../../qtbase/src/corelib/kernel/qcoreapplication.h \
		../../qtbase/include/QtCore/qmath.h \
		../../qtbase/src/corelib/kernel/qmath.h \
		../../qtbase/include/QtCore/qmetaobject.h \
		../../qtbase/src/corelib/kernel/qmetaobject.h \
		../../qtbase/include/QtCore/qmimedata.h \
		../../qtbase/src/corelib/kernel/qmimedata.h \
		../../qtbase/include/QtCore/qobjectcleanuphandler.h \
		../../qtbase/src/corelib/kernel/qobjectcleanuphandler.h \
		../../qtbase/include/QtCore/qpointer.h \
		../../qtbase/src/corelib/kernel/qpointer.h \
		../../qtbase/include/QtCore/qsharedpointer.h \
		../../qtbase/src/corelib/tools/qsharedpointer.h \
		../../qtbase/include/QtCore/qsharedpointer_impl.h \
		../../qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../qtbase/include/QtCore/qsharedmemory.h \
		../../qtbase/src/corelib/kernel/qsharedmemory.h \
		../../qtbase/include/QtCore/qsignalmapper.h \
		../../qtbase/src/corelib/kernel/qsignalmapper.h \
		../../qtbase/include/QtCore/qsocketnotifier.h \
		../../qtbase/src/corelib/kernel/qsocketnotifier.h \
		../../qtbase/include/QtCore/qsystemsemaphore.h \
		../../qtbase/src/corelib/kernel/qsystemsemaphore.h \
		../../qtbase/include/QtCore/qtimer.h \
		../../qtbase/src/corelib/kernel/qtimer.h \
		../../qtbase/include/QtCore/qtranslator.h \
		../../qtbase/src/corelib/kernel/qtranslator.h \
		../../qtbase/include/QtCore/qwineventnotifier.h \
		../../qtbase/src/corelib/kernel/qwineventnotifier.h \
		../../qtbase/include/QtCore/qmimedatabase.h \
		../../qtbase/src/corelib/mimetypes/qmimedatabase.h \
		../../qtbase/include/QtCore/qmimetype.h \
		../../qtbase/src/corelib/mimetypes/qmimetype.h \
		../../qtbase/include/QtCore/qfactoryinterface.h \
		../../qtbase/src/corelib/plugin/qfactoryinterface.h \
		../../qtbase/include/QtCore/qlibrary.h \
		../../qtbase/src/corelib/plugin/qlibrary.h \
		../../qtbase/include/QtCore/qplugin.h \
		../../qtbase/src/corelib/plugin/qplugin.h \
		../../qtbase/include/QtCore/qpluginloader.h \
		../../qtbase/src/corelib/plugin/qpluginloader.h \
		../../qtbase/include/QtCore/quuid.h \
		../../qtbase/src/corelib/plugin/quuid.h \
		../../qtbase/include/QtCore/qabstractstate.h \
		../../qtbase/src/corelib/statemachine/qabstractstate.h \
		../../qtbase/include/QtCore/qabstracttransition.h \
		../../qtbase/src/corelib/statemachine/qabstracttransition.h \
		../../qtbase/include/QtCore/qeventtransition.h \
		../../qtbase/src/corelib/statemachine/qeventtransition.h \
		../../qtbase/include/QtCore/qfinalstate.h \
		../../qtbase/src/corelib/statemachine/qfinalstate.h \
		../../qtbase/include/QtCore/qhistorystate.h \
		../../qtbase/src/corelib/statemachine/qhistorystate.h \
		../../qtbase/include/QtCore/qsignaltransition.h \
		../../qtbase/src/corelib/statemachine/qsignaltransition.h \
		../../qtbase/include/QtCore/qstate.h \
		../../qtbase/src/corelib/statemachine/qstate.h \
		../../qtbase/include/QtCore/qstatemachine.h \
		../../qtbase/src/corelib/statemachine/qstatemachine.h \
		../../qtbase/include/QtCore/qexception.h \
		../../qtbase/src/corelib/thread/qexception.h \
		../../qtbase/include/QtCore/qfuture.h \
		../../qtbase/src/corelib/thread/qfuture.h \
		../../qtbase/include/QtCore/qfutureinterface.h \
		../../qtbase/src/corelib/thread/qfutureinterface.h \
		../../qtbase/include/QtCore/qrunnable.h \
		../../qtbase/src/corelib/thread/qrunnable.h \
		../../qtbase/include/QtCore/qresultstore.h \
		../../qtbase/src/corelib/thread/qresultstore.h \
		../../qtbase/include/QtCore/qfuturesynchronizer.h \
		../../qtbase/src/corelib/thread/qfuturesynchronizer.h \
		../../qtbase/include/QtCore/qfuturewatcher.h \
		../../qtbase/src/corelib/thread/qfuturewatcher.h \
		../../qtbase/include/QtCore/qreadwritelock.h \
		../../qtbase/src/corelib/thread/qreadwritelock.h \
		../../qtbase/include/QtCore/qsemaphore.h \
		../../qtbase/src/corelib/thread/qsemaphore.h \
		../../qtbase/include/QtCore/qthread.h \
		../../qtbase/src/corelib/thread/qthread.h \
		../../qtbase/include/QtCore/qthreadpool.h \
		../../qtbase/src/corelib/thread/qthreadpool.h \
		../../qtbase/include/QtCore/qthreadstorage.h \
		../../qtbase/src/corelib/thread/qthreadstorage.h \
		../../qtbase/include/QtCore/qwaitcondition.h \
		../../qtbase/src/corelib/thread/qwaitcondition.h \
		../../qtbase/include/QtCore/qarraydataops.h \
		../../qtbase/src/corelib/tools/qarraydataops.h \
		../../qtbase/include/QtCore/qarraydatapointer.h \
		../../qtbase/src/corelib/tools/qarraydatapointer.h \
		../../qtbase/include/QtCore/qbitarray.h \
		../../qtbase/src/corelib/tools/qbitarray.h \
		../../qtbase/include/QtCore/qbytearraymatcher.h \
		../../qtbase/src/corelib/tools/qbytearraymatcher.h \
		../../qtbase/include/QtCore/qcache.h \
		../../qtbase/src/corelib/tools/qcache.h \
		../../qtbase/include/QtCore/qcollator.h \
		../../qtbase/src/corelib/tools/qcollator.h \
		../../qtbase/include/QtCore/qcommandlineoption.h \
		../../qtbase/src/corelib/tools/qcommandlineoption.h \
		../../qtbase/include/QtCore/qcommandlineparser.h \
		../../qtbase/src/corelib/tools/qcommandlineparser.h \
		../../qtbase/include/QtCore/qcryptographichash.h \
		../../qtbase/src/corelib/tools/qcryptographichash.h \
		../../qtbase/include/QtCore/qelapsedtimer.h \
		../../qtbase/src/corelib/tools/qelapsedtimer.h \
		../../qtbase/include/QtCore/qline.h \
		../../qtbase/src/corelib/tools/qline.h \
		../../qtbase/include/QtCore/qlinkedlist.h \
		../../qtbase/src/corelib/tools/qlinkedlist.h \
		../../qtbase/include/QtCore/qmargins.h \
		../../qtbase/src/corelib/tools/qmargins.h \
		../../qtbase/include/QtCore/qmessageauthenticationcode.h \
		../../qtbase/src/corelib/tools/qmessageauthenticationcode.h \
		../../qtbase/include/QtCore/qqueue.h \
		../../qtbase/src/corelib/tools/qqueue.h \
		../../qtbase/include/QtCore/qrect.h \
		../../qtbase/src/corelib/tools/qrect.h \
		../../qtbase/include/QtCore/qsize.h \
		../../qtbase/src/corelib/tools/qsize.h \
		../../qtbase/include/QtCore/qregularexpression.h \
		../../qtbase/src/corelib/tools/qregularexpression.h \
		../../qtbase/include/QtCore/qscopedvaluerollback.h \
		../../qtbase/src/corelib/tools/qscopedvaluerollback.h \
		../../qtbase/include/QtCore/qstack.h \
		../../qtbase/src/corelib/tools/qstack.h \
		../../qtbase/include/QtCore/qtextboundaryfinder.h \
		../../qtbase/src/corelib/tools/qtextboundaryfinder.h \
		../../qtbase/include/QtCore/qtimeline.h \
		../../qtbase/src/corelib/tools/qtimeline.h \
		../../qtbase/include/QtCore/qtimezone.h \
		../../qtbase/src/corelib/tools/qtimezone.h \
		../../qtbase/include/QtCore/qversionnumber.h \
		../../qtbase/src/corelib/tools/qversionnumber.h \
		../../qtbase/include/QtCore/qxmlstream.h \
		../../qtbase/src/corelib/xml/qxmlstream.h \
		../../qtbase/include/QtCore/qtcoreversion.h \
		../../qtbase/include/QtCore/QDebug \
		../../qtbase/include/QtCore/QThread \
		Consolereader.h \
		main.cpp
	/Users/Roy/raspi/qtbase/bin/moc $(DEFINES) -I/Users/Roy/raspi/qtbase/mkspecs/devices/linux-rasp-pi2-g++ -I/Users/Roy/raspi/projects/RPi_Console -I/usr/include/linux -I/Users/Roy/raspi/qtbase/include -I/Users/Roy/raspi/qtbase/include/QtCore -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.9.1 -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.9.1/arm-linux-gnueabihf -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.9.1/backward -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.9.1/include -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.9.1/include-fixed -I/usr/local/linaro/arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include -I/Users/Roy/raspi/sysroot/usr/include/arm-linux-gnueabihf -I/Users/Roy/raspi/sysroot/usr/include main.cpp -o main.moc

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean 

####### Compile

main.o: main.cpp ../../qtbase/include/QtCore/QtCore \
		../../qtbase/include/QtCore/QtCoreDepends \
		../../qtbase/include/QtCore/qabstractanimation.h \
		../../qtbase/src/corelib/animation/qabstractanimation.h \
		../../qtbase/include/QtCore/qobject.h \
		../../qtbase/src/corelib/kernel/qobject.h \
		../../qtbase/include/QtCore/qobjectdefs.h \
		../../qtbase/src/corelib/kernel/qobjectdefs.h \
		../../qtbase/include/QtCore/qnamespace.h \
		../../qtbase/src/corelib/global/qnamespace.h \
		../../qtbase/include/QtCore/qglobal.h \
		../../qtbase/src/corelib/global/qglobal.h \
		../../qtbase/include/QtCore/qconfig.h \
		../../qtbase/src/corelib/global/qconfig.h \
		../../qtbase/include/QtCore/qfeatures.h \
		../../qtbase/src/corelib/global/qfeatures.h \
		../../qtbase/include/QtCore/qsystemdetection.h \
		../../qtbase/src/corelib/global/qsystemdetection.h \
		../../qtbase/include/QtCore/qprocessordetection.h \
		../../qtbase/src/corelib/global/qprocessordetection.h \
		../../qtbase/include/QtCore/qcompilerdetection.h \
		../../qtbase/src/corelib/global/qcompilerdetection.h \
		../../qtbase/include/QtCore/qtypeinfo.h \
		../../qtbase/src/corelib/global/qtypeinfo.h \
		../../qtbase/include/QtCore/qtypetraits.h \
		../../qtbase/src/corelib/global/qtypetraits.h \
		../../qtbase/include/QtCore/qisenum.h \
		../../qtbase/src/corelib/global/qisenum.h \
		../../qtbase/include/QtCore/qsysinfo.h \
		../../qtbase/src/corelib/global/qsysinfo.h \
		../../qtbase/include/QtCore/qlogging.h \
		../../qtbase/src/corelib/global/qlogging.h \
		../../qtbase/include/QtCore/qflags.h \
		../../qtbase/src/corelib/global/qflags.h \
		../../qtbase/include/QtCore/qatomic.h \
		../../qtbase/src/corelib/thread/qatomic.h \
		../../qtbase/include/QtCore/qbasicatomic.h \
		../../qtbase/src/corelib/thread/qbasicatomic.h \
		../../qtbase/include/QtCore/qatomic_bootstrap.h \
		../../qtbase/src/corelib/arch/qatomic_bootstrap.h \
		../../qtbase/include/QtCore/qgenericatomic.h \
		../../qtbase/src/corelib/thread/qgenericatomic.h \
		../../qtbase/include/QtCore/qatomic_cxx11.h \
		../../qtbase/src/corelib/arch/qatomic_cxx11.h \
		../../qtbase/include/QtCore/qatomic_gcc.h \
		../../qtbase/src/corelib/arch/qatomic_gcc.h \
		../../qtbase/include/QtCore/qatomic_msvc.h \
		../../qtbase/src/corelib/arch/qatomic_msvc.h \
		../../qtbase/include/QtCore/qatomic_armv7.h \
		../../qtbase/src/corelib/arch/qatomic_armv7.h \
		../../qtbase/include/QtCore/qatomic_armv6.h \
		../../qtbase/src/corelib/arch/qatomic_armv6.h \
		../../qtbase/include/QtCore/qatomic_armv5.h \
		../../qtbase/src/corelib/arch/qatomic_armv5.h \
		../../qtbase/include/QtCore/qatomic_ia64.h \
		../../qtbase/src/corelib/arch/qatomic_ia64.h \
		../../qtbase/include/QtCore/qatomic_x86.h \
		../../qtbase/src/corelib/arch/qatomic_x86.h \
		../../qtbase/include/QtCore/qatomic_unix.h \
		../../qtbase/src/corelib/arch/qatomic_unix.h \
		../../qtbase/include/QtCore/qglobalstatic.h \
		../../qtbase/src/corelib/global/qglobalstatic.h \
		../../qtbase/include/QtCore/qmutex.h \
		../../qtbase/src/corelib/thread/qmutex.h \
		../../qtbase/include/QtCore/qnumeric.h \
		../../qtbase/src/corelib/global/qnumeric.h \
		../../qtbase/include/QtCore/qversiontagging.h \
		../../qtbase/src/corelib/global/qversiontagging.h \
		../../qtbase/include/QtCore/qobjectdefs_impl.h \
		../../qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../qtbase/include/QtCore/qstring.h \
		../../qtbase/src/corelib/tools/qstring.h \
		../../qtbase/include/QtCore/qchar.h \
		../../qtbase/src/corelib/tools/qchar.h \
		../../qtbase/include/QtCore/qbytearray.h \
		../../qtbase/src/corelib/tools/qbytearray.h \
		../../qtbase/include/QtCore/qrefcount.h \
		../../qtbase/src/corelib/tools/qrefcount.h \
		../../qtbase/include/QtCore/qarraydata.h \
		../../qtbase/src/corelib/tools/qarraydata.h \
		../../qtbase/include/QtCore/qstringbuilder.h \
		../../qtbase/src/corelib/tools/qstringbuilder.h \
		../../qtbase/include/QtCore/qlist.h \
		../../qtbase/src/corelib/tools/qlist.h \
		../../qtbase/include/QtCore/qalgorithms.h \
		../../qtbase/src/corelib/tools/qalgorithms.h \
		../../qtbase/include/QtCore/qiterator.h \
		../../qtbase/src/corelib/tools/qiterator.h \
		../../qtbase/include/QtCore/qhashfunctions.h \
		../../qtbase/src/corelib/tools/qhashfunctions.h \
		../../qtbase/include/QtCore/qpair.h \
		../../qtbase/src/corelib/tools/qpair.h \
		../../qtbase/include/QtCore/qbytearraylist.h \
		../../qtbase/src/corelib/tools/qbytearraylist.h \
		../../qtbase/include/QtCore/qstringlist.h \
		../../qtbase/src/corelib/tools/qstringlist.h \
		../../qtbase/include/QtCore/qregexp.h \
		../../qtbase/src/corelib/tools/qregexp.h \
		../../qtbase/include/QtCore/qstringmatcher.h \
		../../qtbase/src/corelib/tools/qstringmatcher.h \
		../../qtbase/include/QtCore/qcoreevent.h \
		../../qtbase/src/corelib/kernel/qcoreevent.h \
		../../qtbase/include/QtCore/qscopedpointer.h \
		../../qtbase/src/corelib/tools/qscopedpointer.h \
		../../qtbase/include/QtCore/qmetatype.h \
		../../qtbase/src/corelib/kernel/qmetatype.h \
		../../qtbase/include/QtCore/qvarlengtharray.h \
		../../qtbase/src/corelib/tools/qvarlengtharray.h \
		../../qtbase/include/QtCore/qcontainerfwd.h \
		../../qtbase/src/corelib/tools/qcontainerfwd.h \
		../../qtbase/include/QtCore/qobject_impl.h \
		../../qtbase/src/corelib/kernel/qobject_impl.h \
		../../qtbase/include/QtCore/qanimationgroup.h \
		../../qtbase/src/corelib/animation/qanimationgroup.h \
		../../qtbase/include/QtCore/qparallelanimationgroup.h \
		../../qtbase/src/corelib/animation/qparallelanimationgroup.h \
		../../qtbase/include/QtCore/qpauseanimation.h \
		../../qtbase/src/corelib/animation/qpauseanimation.h \
		../../qtbase/include/QtCore/qpropertyanimation.h \
		../../qtbase/src/corelib/animation/qpropertyanimation.h \
		../../qtbase/include/QtCore/qvariantanimation.h \
		../../qtbase/src/corelib/animation/qvariantanimation.h \
		../../qtbase/include/QtCore/qeasingcurve.h \
		../../qtbase/src/corelib/tools/qeasingcurve.h \
		../../qtbase/include/QtCore/qvector.h \
		../../qtbase/src/corelib/tools/qvector.h \
		../../qtbase/include/QtCore/qpoint.h \
		../../qtbase/src/corelib/tools/qpoint.h \
		../../qtbase/include/QtCore/qvariant.h \
		../../qtbase/src/corelib/kernel/qvariant.h \
		../../qtbase/include/QtCore/qmap.h \
		../../qtbase/src/corelib/tools/qmap.h \
		../../qtbase/include/QtCore/qdebug.h \
		../../qtbase/src/corelib/io/qdebug.h \
		../../qtbase/include/QtCore/qhash.h \
		../../qtbase/src/corelib/tools/qhash.h \
		../../qtbase/include/QtCore/qtextstream.h \
		../../qtbase/src/corelib/io/qtextstream.h \
		../../qtbase/include/QtCore/qiodevice.h \
		../../qtbase/src/corelib/io/qiodevice.h \
		../../qtbase/include/QtCore/qlocale.h \
		../../qtbase/src/corelib/tools/qlocale.h \
		../../qtbase/include/QtCore/qshareddata.h \
		../../qtbase/src/corelib/tools/qshareddata.h \
		../../qtbase/include/QtCore/qset.h \
		../../qtbase/src/corelib/tools/qset.h \
		../../qtbase/include/QtCore/qcontiguouscache.h \
		../../qtbase/src/corelib/tools/qcontiguouscache.h \
		../../qtbase/include/QtCore/qsequentialanimationgroup.h \
		../../qtbase/src/corelib/animation/qsequentialanimationgroup.h \
		../../qtbase/include/QtCore/qtextcodec.h \
		../../qtbase/src/corelib/codecs/qtextcodec.h \
		../../qtbase/include/QtCore/qendian.h \
		../../qtbase/src/corelib/global/qendian.h \
		../../qtbase/include/QtCore/qlibraryinfo.h \
		../../qtbase/src/corelib/global/qlibraryinfo.h \
		../../qtbase/include/QtCore/qdatetime.h \
		../../qtbase/src/corelib/tools/qdatetime.h \
		../../qtbase/include/QtCore/qbuffer.h \
		../../qtbase/src/corelib/io/qbuffer.h \
		../../qtbase/include/QtCore/qdatastream.h \
		../../qtbase/src/corelib/io/qdatastream.h \
		../../qtbase/include/QtCore/qdir.h \
		../../qtbase/src/corelib/io/qdir.h \
		../../qtbase/include/QtCore/qfileinfo.h \
		../../qtbase/src/corelib/io/qfileinfo.h \
		../../qtbase/include/QtCore/qfile.h \
		../../qtbase/src/corelib/io/qfile.h \
		../../qtbase/include/QtCore/qfiledevice.h \
		../../qtbase/src/corelib/io/qfiledevice.h \
		../../qtbase/include/QtCore/qdiriterator.h \
		../../qtbase/src/corelib/io/qdiriterator.h \
		../../qtbase/include/QtCore/qfileselector.h \
		../../qtbase/src/corelib/io/qfileselector.h \
		../../qtbase/include/QtCore/QObject \
		../../qtbase/include/QtCore/QStringList \
		../../qtbase/include/QtCore/qfilesystemwatcher.h \
		../../qtbase/src/corelib/io/qfilesystemwatcher.h \
		../../qtbase/include/QtCore/qlockfile.h \
		../../qtbase/src/corelib/io/qlockfile.h \
		../../qtbase/include/QtCore/qloggingcategory.h \
		../../qtbase/src/corelib/io/qloggingcategory.h \
		../../qtbase/include/QtCore/qprocess.h \
		../../qtbase/src/corelib/io/qprocess.h \
		../../qtbase/include/QtCore/qresource.h \
		../../qtbase/src/corelib/io/qresource.h \
		../../qtbase/include/QtCore/qsavefile.h \
		../../qtbase/src/corelib/io/qsavefile.h \
		../../qtbase/include/QtCore/qsettings.h \
		../../qtbase/src/corelib/io/qsettings.h \
		../../qtbase/include/QtCore/qstandardpaths.h \
		../../qtbase/src/corelib/io/qstandardpaths.h \
		../../qtbase/include/QtCore/qstorageinfo.h \
		../../qtbase/src/corelib/io/qstorageinfo.h \
		../../qtbase/include/QtCore/qtemporarydir.h \
		../../qtbase/src/corelib/io/qtemporarydir.h \
		../../qtbase/include/QtCore/QScopedPointer \
		../../qtbase/include/QtCore/qtemporaryfile.h \
		../../qtbase/src/corelib/io/qtemporaryfile.h \
		../../qtbase/include/QtCore/qurl.h \
		../../qtbase/src/corelib/io/qurl.h \
		../../qtbase/include/QtCore/qurlquery.h \
		../../qtbase/src/corelib/io/qurlquery.h \
		../../qtbase/include/QtCore/qabstractitemmodel.h \
		../../qtbase/src/corelib/itemmodels/qabstractitemmodel.h \
		../../qtbase/include/QtCore/qabstractproxymodel.h \
		../../qtbase/src/corelib/itemmodels/qabstractproxymodel.h \
		../../qtbase/include/QtCore/qidentityproxymodel.h \
		../../qtbase/src/corelib/itemmodels/qidentityproxymodel.h \
		../../qtbase/include/QtCore/qitemselectionmodel.h \
		../../qtbase/src/corelib/itemmodels/qitemselectionmodel.h \
		../../qtbase/include/QtCore/qsortfilterproxymodel.h \
		../../qtbase/src/corelib/itemmodels/qsortfilterproxymodel.h \
		../../qtbase/include/QtCore/qstringlistmodel.h \
		../../qtbase/src/corelib/itemmodels/qstringlistmodel.h \
		../../qtbase/include/QtCore/qjsonarray.h \
		../../qtbase/src/corelib/json/qjsonarray.h \
		../../qtbase/include/QtCore/qjsonvalue.h \
		../../qtbase/src/corelib/json/qjsonvalue.h \
		../../qtbase/include/QtCore/qjsondocument.h \
		../../qtbase/src/corelib/json/qjsondocument.h \
		../../qtbase/include/QtCore/qjsonobject.h \
		../../qtbase/src/corelib/json/qjsonobject.h \
		../../qtbase/include/QtCore/qabstracteventdispatcher.h \
		../../qtbase/src/corelib/kernel/qabstracteventdispatcher.h \
		../../qtbase/include/QtCore/qeventloop.h \
		../../qtbase/src/corelib/kernel/qeventloop.h \
		../../qtbase/include/QtCore/qabstractnativeeventfilter.h \
		../../qtbase/src/corelib/kernel/qabstractnativeeventfilter.h \
		../../qtbase/include/QtCore/qbasictimer.h \
		../../qtbase/src/corelib/kernel/qbasictimer.h \
		../../qtbase/include/QtCore/qcoreapplication.h \
		../../qtbase/src/corelib/kernel/qcoreapplication.h \
		../../qtbase/include/QtCore/qmath.h \
		../../qtbase/src/corelib/kernel/qmath.h \
		../../qtbase/include/QtCore/qmetaobject.h \
		../../qtbase/src/corelib/kernel/qmetaobject.h \
		../../qtbase/include/QtCore/qmimedata.h \
		../../qtbase/src/corelib/kernel/qmimedata.h \
		../../qtbase/include/QtCore/qobjectcleanuphandler.h \
		../../qtbase/src/corelib/kernel/qobjectcleanuphandler.h \
		../../qtbase/include/QtCore/qpointer.h \
		../../qtbase/src/corelib/kernel/qpointer.h \
		../../qtbase/include/QtCore/qsharedpointer.h \
		../../qtbase/src/corelib/tools/qsharedpointer.h \
		../../qtbase/include/QtCore/qsharedpointer_impl.h \
		../../qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../qtbase/include/QtCore/qsharedmemory.h \
		../../qtbase/src/corelib/kernel/qsharedmemory.h \
		../../qtbase/include/QtCore/qsignalmapper.h \
		../../qtbase/src/corelib/kernel/qsignalmapper.h \
		../../qtbase/include/QtCore/qsocketnotifier.h \
		../../qtbase/src/corelib/kernel/qsocketnotifier.h \
		../../qtbase/include/QtCore/qsystemsemaphore.h \
		../../qtbase/src/corelib/kernel/qsystemsemaphore.h \
		../../qtbase/include/QtCore/qtimer.h \
		../../qtbase/src/corelib/kernel/qtimer.h \
		../../qtbase/include/QtCore/qtranslator.h \
		../../qtbase/src/corelib/kernel/qtranslator.h \
		../../qtbase/include/QtCore/qwineventnotifier.h \
		../../qtbase/src/corelib/kernel/qwineventnotifier.h \
		../../qtbase/include/QtCore/qmimedatabase.h \
		../../qtbase/src/corelib/mimetypes/qmimedatabase.h \
		../../qtbase/include/QtCore/qmimetype.h \
		../../qtbase/src/corelib/mimetypes/qmimetype.h \
		../../qtbase/include/QtCore/qfactoryinterface.h \
		../../qtbase/src/corelib/plugin/qfactoryinterface.h \
		../../qtbase/include/QtCore/qlibrary.h \
		../../qtbase/src/corelib/plugin/qlibrary.h \
		../../qtbase/include/QtCore/qplugin.h \
		../../qtbase/src/corelib/plugin/qplugin.h \
		../../qtbase/include/QtCore/qpluginloader.h \
		../../qtbase/src/corelib/plugin/qpluginloader.h \
		../../qtbase/include/QtCore/quuid.h \
		../../qtbase/src/corelib/plugin/quuid.h \
		../../qtbase/include/QtCore/qabstractstate.h \
		../../qtbase/src/corelib/statemachine/qabstractstate.h \
		../../qtbase/include/QtCore/qabstracttransition.h \
		../../qtbase/src/corelib/statemachine/qabstracttransition.h \
		../../qtbase/include/QtCore/qeventtransition.h \
		../../qtbase/src/corelib/statemachine/qeventtransition.h \
		../../qtbase/include/QtCore/qfinalstate.h \
		../../qtbase/src/corelib/statemachine/qfinalstate.h \
		../../qtbase/include/QtCore/qhistorystate.h \
		../../qtbase/src/corelib/statemachine/qhistorystate.h \
		../../qtbase/include/QtCore/qsignaltransition.h \
		../../qtbase/src/corelib/statemachine/qsignaltransition.h \
		../../qtbase/include/QtCore/qstate.h \
		../../qtbase/src/corelib/statemachine/qstate.h \
		../../qtbase/include/QtCore/qstatemachine.h \
		../../qtbase/src/corelib/statemachine/qstatemachine.h \
		../../qtbase/include/QtCore/qexception.h \
		../../qtbase/src/corelib/thread/qexception.h \
		../../qtbase/include/QtCore/qfuture.h \
		../../qtbase/src/corelib/thread/qfuture.h \
		../../qtbase/include/QtCore/qfutureinterface.h \
		../../qtbase/src/corelib/thread/qfutureinterface.h \
		../../qtbase/include/QtCore/qrunnable.h \
		../../qtbase/src/corelib/thread/qrunnable.h \
		../../qtbase/include/QtCore/qresultstore.h \
		../../qtbase/src/corelib/thread/qresultstore.h \
		../../qtbase/include/QtCore/qfuturesynchronizer.h \
		../../qtbase/src/corelib/thread/qfuturesynchronizer.h \
		../../qtbase/include/QtCore/qfuturewatcher.h \
		../../qtbase/src/corelib/thread/qfuturewatcher.h \
		../../qtbase/include/QtCore/qreadwritelock.h \
		../../qtbase/src/corelib/thread/qreadwritelock.h \
		../../qtbase/include/QtCore/qsemaphore.h \
		../../qtbase/src/corelib/thread/qsemaphore.h \
		../../qtbase/include/QtCore/qthread.h \
		../../qtbase/src/corelib/thread/qthread.h \
		../../qtbase/include/QtCore/qthreadpool.h \
		../../qtbase/src/corelib/thread/qthreadpool.h \
		../../qtbase/include/QtCore/qthreadstorage.h \
		../../qtbase/src/corelib/thread/qthreadstorage.h \
		../../qtbase/include/QtCore/qwaitcondition.h \
		../../qtbase/src/corelib/thread/qwaitcondition.h \
		../../qtbase/include/QtCore/qarraydataops.h \
		../../qtbase/src/corelib/tools/qarraydataops.h \
		../../qtbase/include/QtCore/qarraydatapointer.h \
		../../qtbase/src/corelib/tools/qarraydatapointer.h \
		../../qtbase/include/QtCore/qbitarray.h \
		../../qtbase/src/corelib/tools/qbitarray.h \
		../../qtbase/include/QtCore/qbytearraymatcher.h \
		../../qtbase/src/corelib/tools/qbytearraymatcher.h \
		../../qtbase/include/QtCore/qcache.h \
		../../qtbase/src/corelib/tools/qcache.h \
		../../qtbase/include/QtCore/qcollator.h \
		../../qtbase/src/corelib/tools/qcollator.h \
		../../qtbase/include/QtCore/qcommandlineoption.h \
		../../qtbase/src/corelib/tools/qcommandlineoption.h \
		../../qtbase/include/QtCore/qcommandlineparser.h \
		../../qtbase/src/corelib/tools/qcommandlineparser.h \
		../../qtbase/include/QtCore/qcryptographichash.h \
		../../qtbase/src/corelib/tools/qcryptographichash.h \
		../../qtbase/include/QtCore/qelapsedtimer.h \
		../../qtbase/src/corelib/tools/qelapsedtimer.h \
		../../qtbase/include/QtCore/qline.h \
		../../qtbase/src/corelib/tools/qline.h \
		../../qtbase/include/QtCore/qlinkedlist.h \
		../../qtbase/src/corelib/tools/qlinkedlist.h \
		../../qtbase/include/QtCore/qmargins.h \
		../../qtbase/src/corelib/tools/qmargins.h \
		../../qtbase/include/QtCore/qmessageauthenticationcode.h \
		../../qtbase/src/corelib/tools/qmessageauthenticationcode.h \
		../../qtbase/include/QtCore/qqueue.h \
		../../qtbase/src/corelib/tools/qqueue.h \
		../../qtbase/include/QtCore/qrect.h \
		../../qtbase/src/corelib/tools/qrect.h \
		../../qtbase/include/QtCore/qsize.h \
		../../qtbase/src/corelib/tools/qsize.h \
		../../qtbase/include/QtCore/qregularexpression.h \
		../../qtbase/src/corelib/tools/qregularexpression.h \
		../../qtbase/include/QtCore/qscopedvaluerollback.h \
		../../qtbase/src/corelib/tools/qscopedvaluerollback.h \
		../../qtbase/include/QtCore/qstack.h \
		../../qtbase/src/corelib/tools/qstack.h \
		../../qtbase/include/QtCore/qtextboundaryfinder.h \
		../../qtbase/src/corelib/tools/qtextboundaryfinder.h \
		../../qtbase/include/QtCore/qtimeline.h \
		../../qtbase/src/corelib/tools/qtimeline.h \
		../../qtbase/include/QtCore/qtimezone.h \
		../../qtbase/src/corelib/tools/qtimezone.h \
		../../qtbase/include/QtCore/qversionnumber.h \
		../../qtbase/src/corelib/tools/qversionnumber.h \
		../../qtbase/include/QtCore/qxmlstream.h \
		../../qtbase/src/corelib/xml/qxmlstream.h \
		../../qtbase/include/QtCore/qtcoreversion.h \
		../../qtbase/include/QtCore/QDebug \
		../../qtbase/include/QtCore/QThread \
		Consolereader.h \
		main.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Consolereader.o: Consolereader.cpp ConsoleReader.h \
		../../qtbase/include/QtCore/QThread \
		../../qtbase/include/QtCore/qthread.h \
		../../qtbase/src/corelib/thread/qthread.h \
		../../qtbase/include/QtCore/qobject.h \
		../../qtbase/src/corelib/kernel/qobject.h \
		../../qtbase/include/QtCore/qobjectdefs.h \
		../../qtbase/src/corelib/kernel/qobjectdefs.h \
		../../qtbase/include/QtCore/qnamespace.h \
		../../qtbase/src/corelib/global/qnamespace.h \
		../../qtbase/include/QtCore/qglobal.h \
		../../qtbase/src/corelib/global/qglobal.h \
		../../qtbase/include/QtCore/qconfig.h \
		../../qtbase/src/corelib/global/qconfig.h \
		../../qtbase/include/QtCore/qfeatures.h \
		../../qtbase/src/corelib/global/qfeatures.h \
		../../qtbase/include/QtCore/qsystemdetection.h \
		../../qtbase/src/corelib/global/qsystemdetection.h \
		../../qtbase/include/QtCore/qprocessordetection.h \
		../../qtbase/src/corelib/global/qprocessordetection.h \
		../../qtbase/include/QtCore/qcompilerdetection.h \
		../../qtbase/src/corelib/global/qcompilerdetection.h \
		../../qtbase/include/QtCore/qtypeinfo.h \
		../../qtbase/src/corelib/global/qtypeinfo.h \
		../../qtbase/include/QtCore/qtypetraits.h \
		../../qtbase/src/corelib/global/qtypetraits.h \
		../../qtbase/include/QtCore/qisenum.h \
		../../qtbase/src/corelib/global/qisenum.h \
		../../qtbase/include/QtCore/qsysinfo.h \
		../../qtbase/src/corelib/global/qsysinfo.h \
		../../qtbase/include/QtCore/qlogging.h \
		../../qtbase/src/corelib/global/qlogging.h \
		../../qtbase/include/QtCore/qflags.h \
		../../qtbase/src/corelib/global/qflags.h \
		../../qtbase/include/QtCore/qatomic.h \
		../../qtbase/src/corelib/thread/qatomic.h \
		../../qtbase/include/QtCore/qbasicatomic.h \
		../../qtbase/src/corelib/thread/qbasicatomic.h \
		../../qtbase/include/QtCore/qatomic_bootstrap.h \
		../../qtbase/src/corelib/arch/qatomic_bootstrap.h \
		../../qtbase/include/QtCore/qgenericatomic.h \
		../../qtbase/src/corelib/thread/qgenericatomic.h \
		../../qtbase/include/QtCore/qatomic_cxx11.h \
		../../qtbase/src/corelib/arch/qatomic_cxx11.h \
		../../qtbase/include/QtCore/qatomic_gcc.h \
		../../qtbase/src/corelib/arch/qatomic_gcc.h \
		../../qtbase/include/QtCore/qatomic_msvc.h \
		../../qtbase/src/corelib/arch/qatomic_msvc.h \
		../../qtbase/include/QtCore/qatomic_armv7.h \
		../../qtbase/src/corelib/arch/qatomic_armv7.h \
		../../qtbase/include/QtCore/qatomic_armv6.h \
		../../qtbase/src/corelib/arch/qatomic_armv6.h \
		../../qtbase/include/QtCore/qatomic_armv5.h \
		../../qtbase/src/corelib/arch/qatomic_armv5.h \
		../../qtbase/include/QtCore/qatomic_ia64.h \
		../../qtbase/src/corelib/arch/qatomic_ia64.h \
		../../qtbase/include/QtCore/qatomic_x86.h \
		../../qtbase/src/corelib/arch/qatomic_x86.h \
		../../qtbase/include/QtCore/qatomic_unix.h \
		../../qtbase/src/corelib/arch/qatomic_unix.h \
		../../qtbase/include/QtCore/qglobalstatic.h \
		../../qtbase/src/corelib/global/qglobalstatic.h \
		../../qtbase/include/QtCore/qmutex.h \
		../../qtbase/src/corelib/thread/qmutex.h \
		../../qtbase/include/QtCore/qnumeric.h \
		../../qtbase/src/corelib/global/qnumeric.h \
		../../qtbase/include/QtCore/qversiontagging.h \
		../../qtbase/src/corelib/global/qversiontagging.h \
		../../qtbase/include/QtCore/qobjectdefs_impl.h \
		../../qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../qtbase/include/QtCore/qstring.h \
		../../qtbase/src/corelib/tools/qstring.h \
		../../qtbase/include/QtCore/qchar.h \
		../../qtbase/src/corelib/tools/qchar.h \
		../../qtbase/include/QtCore/qbytearray.h \
		../../qtbase/src/corelib/tools/qbytearray.h \
		../../qtbase/include/QtCore/qrefcount.h \
		../../qtbase/src/corelib/tools/qrefcount.h \
		../../qtbase/include/QtCore/qarraydata.h \
		../../qtbase/src/corelib/tools/qarraydata.h \
		../../qtbase/include/QtCore/qstringbuilder.h \
		../../qtbase/src/corelib/tools/qstringbuilder.h \
		../../qtbase/include/QtCore/qlist.h \
		../../qtbase/src/corelib/tools/qlist.h \
		../../qtbase/include/QtCore/qalgorithms.h \
		../../qtbase/src/corelib/tools/qalgorithms.h \
		../../qtbase/include/QtCore/qiterator.h \
		../../qtbase/src/corelib/tools/qiterator.h \
		../../qtbase/include/QtCore/qhashfunctions.h \
		../../qtbase/src/corelib/tools/qhashfunctions.h \
		../../qtbase/include/QtCore/qpair.h \
		../../qtbase/src/corelib/tools/qpair.h \
		../../qtbase/include/QtCore/qbytearraylist.h \
		../../qtbase/src/corelib/tools/qbytearraylist.h \
		../../qtbase/include/QtCore/qstringlist.h \
		../../qtbase/src/corelib/tools/qstringlist.h \
		../../qtbase/include/QtCore/qregexp.h \
		../../qtbase/src/corelib/tools/qregexp.h \
		../../qtbase/include/QtCore/qstringmatcher.h \
		../../qtbase/src/corelib/tools/qstringmatcher.h \
		../../qtbase/include/QtCore/qcoreevent.h \
		../../qtbase/src/corelib/kernel/qcoreevent.h \
		../../qtbase/include/QtCore/qscopedpointer.h \
		../../qtbase/src/corelib/tools/qscopedpointer.h \
		../../qtbase/include/QtCore/qmetatype.h \
		../../qtbase/src/corelib/kernel/qmetatype.h \
		../../qtbase/include/QtCore/qvarlengtharray.h \
		../../qtbase/src/corelib/tools/qvarlengtharray.h \
		../../qtbase/include/QtCore/qcontainerfwd.h \
		../../qtbase/src/corelib/tools/qcontainerfwd.h \
		../../qtbase/include/QtCore/qobject_impl.h \
		../../qtbase/src/corelib/kernel/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Consolereader.o Consolereader.cpp

PCA9685.o: ../PCA9685/PCA9685.cpp ../PCA9685/PCA9685.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PCA9685.o ../PCA9685/PCA9685.cpp

moc_Consolereader.o: moc_Consolereader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Consolereader.o moc_Consolereader.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/pi || mkdir -p $(INSTALL_ROOT)/home/pi
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/pi/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/pi/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/pi/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/pi/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

